data:extend(
{
    {
        type = "fluid",
        name = "paint-r",
        icon = "__shapeztorio__/graphics/icons/fluid/paint-r.png",
        subgroup = "shapez",
        default_temperature = 21,
        max_temperature = 200,
        heat_capacity = "2kJ",
        base_color = {1, 0.13, 0},
        flow_color = {1.4, 0.6, 0.3},
        auto_barrel = true,
    },
    {
        type = "fluid",
        name = "paint-g",
        icon = "__shapeztorio__/graphics/icons/fluid/paint-g.png",
        subgroup = "shapez",
        default_temperature = 21,
        max_temperature = 200,
        heat_capacity = "2kJ",
        base_color = {0.1, 1, 0.4}, 
        flow_color = {0, 0.3, 0.1},
        auto_barrel = true,
    },
    {
        type = "fluid",
        name = "paint-b",
        icon = "__shapeztorio__/graphics/icons/fluid/paint-b.png",
        subgroup = "shapez",
        default_temperature = 21,
        max_temperature = 200,
        heat_capacity = "2kJ",
        base_color = {1, 0.4, 1}, 
        flow_color = {0.3, 0.1, 0.3},
        auto_barrel = true,
    },
    {
        type = "fluid",
        name = "paint-w",
        icon = "__shapeztorio__/graphics/icons/fluid/paint-b.png",
        subgroup = "shapez",
        default_temperature = 21,
        max_temperature = 200,
        heat_capacity = "2kJ",
        base_color = {1, 0.4, 1}, 
        flow_color = {0.3, 0.1, 0.3},
        auto_barrel = true,
    },
})