require("__shapeztorio__/prototypes/item-groups")
require("__shapeztorio__/prototypes/recipe-category")
require("__shapeztorio__/prototypes/item")
require("__shapeztorio__/prototypes/shapez")
require("__shapeztorio__/prototypes/fluid")
require("__shapeztorio__/prototypes/entities")
require("__shapeztorio__/prototypes/technology")
require("__shapeztorio__/prototypes/recipe")
